In [1]:
import numpy as np
import pandas as pd

In [2]:
errors = pd.read_csv("../Errors.csv")
errors.head()

          date  strike  maturity  true_price  computed_price  abs_error
0  02-Jan-2025    1380  0.153425       34.80         4.03268  30.767300
1  02-Jan-2025    1230  0.153425       52.80        53.11110   0.311095
2  02-Jan-2025    1090  0.153425      148.30       179.31200  31.011900
3  02-Jan-2025    1080  0.153425      216.25       188.69900  27.550900
4  02-Jan-2025    1210  0.153425       66.20        70.01150   3.811520

In [3]:
max_abs = errors['abs_error'].max()
max_abs

np.float64(125.265)

In [4]:
errors_sorted = errors.sort_values(by="abs_error", ascending=True)
errors_sorted

            date  strike  maturity  true_price  computed_price   abs_error
310  07-Jan-2025    1380  0.139726        6.30        6.329400    0.029397
272  06-Jan-2025    1460  0.065753        0.50        0.458334    0.041666
348  07-Jan-2025    1380  0.063014        1.25        1.207150    0.042849
51   02-Jan-2025    1330  0.076712        3.75        3.799980    0.049976
305  06-Jan-2025    1500  0.065753        0.30        0.241055    0.058945
..           ...     ...       ...         ...             ...         ...
328  07-Jan-2025    1060  0.063014      292.85      186.799000  106.051000
332  07-Jan-2025    1080  0.063014      274.00      166.968000  107.032000
268  06-Jan-2025    1080  0.065753      274.00      148.808000  125.192000
263  06-Jan-2025    1060  0.065753      292.85      167.596000  125.254000
265  06-Jan-2025    1020  0.065753      331.15      205.885000  125.265000

[518 rows x 6 columns]