In [5]:
import numpy as np
import pandas as pd

In [6]:
errors = pd.read_csv("../single_state_errors.csv")
errors.head()

          date  strike  maturity  true_price  computed_price  abs_error
0  01-Jan-2025    1260  0.232877       53.95         67.4726    13.5226
1  01-Jan-2025    1140  0.232877      121.30        135.1330    13.8329
2  01-Jan-2025    1120  0.232877      135.80        149.3110    13.5110
3  01-Jan-2025    1360  0.232877       23.20         33.3917    10.1917
4  01-Jan-2025    1240  0.232877       62.75         76.6271    13.8771

In [7]:
max_abs = errors['abs_error'].max()
max_abs

np.float64(123.374)

In [8]:
errors_sorted = errors.sort_values(by="abs_error", ascending=True)
errors_sorted

            date  strike  maturity  true_price  computed_price   abs_error
121  02-Jan-2025    1480  0.076712        0.40        0.381182    0.018818
122  02-Jan-2025    1460  0.076712        0.55        0.639625    0.089625
62   01-Jan-2025    1460  0.079452        0.50        0.374953    0.125047
155  02-Jan-2025    1500  0.076712        0.35        0.222403    0.127597
65   01-Jan-2025    1440  0.079452        0.50        0.629321    0.129321
..           ...     ...       ...         ...             ...         ...
150  02-Jan-2025    1120  0.076712      237.15      132.404000  104.746000
57   01-Jan-2025    1020  0.079452      331.15      208.939000  122.211000
56   01-Jan-2025    1060  0.079452      292.85      169.804000  123.046000
90   01-Jan-2025    1120  0.079452      237.15      113.859000  123.291000
60   01-Jan-2025    1080  0.079452      274.00      150.626000  123.374000

[188 rows x 6 columns]